---

- name: Allow anonymous bind
  community.general.ldap_attrs:
    dn: 'cn=config'
    attributes:
      olcDisallows: 'bind_anon'
      olcRequires: 'authc'
    state: 'absent'
  when: slapd_anonymous_bind|bool

- name: Allow anonymous bind (frontend)
  community.general.ldap_attrs:
    dn: 'olcDatabase={-1}frontend,cn=config'
    attributes:
      olcRequires: 'authc'
    state: 'absent'
  when: slapd_anonymous_bind|bool

- name: Deny anonymous bind, require authentication
  community.general.ldap_attrs:
    dn: 'cn=config'
    attributes:
      olcDisallows: 'bind_anon'
      olcRequires: 'authc'
    state: 'exact'
  when: not slapd_anonymous_bind|bool

- name: Deny anonymous bind, require authentication (frontend)
  community.general.ldap_attrs:
    dn: 'olcDatabase={-1}frontend,cn=config'
    attributes:
      olcRequires: 'authc'
    state: 'exact'
  when: not slapd_anonymous_bind|bool
