---

- name: Install ldapscripts packages
  ansible.builtin.apt:
    name:
      - 'ldapscripts'
      - 'ldap-utils'
      - 'pwgen'
    state: 'present'
    install_recommends: false

- name: Configure ldapscripts
  ansible.builtin.template:
    src: 'etc/ldapscripts/ldapscripts.conf.j2'
    dest: '/etc/ldapscripts/ldapscripts.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure ldapscripts password
  ansible.builtin.template:
    src: 'etc/ldapscripts/ldapscripts.passwd.j2'
    dest: '/etc/ldapscripts/ldapscripts.passwd'
    owner: 'root'
    group: 'root'
    mode: '0640'
  no_log: true
