---
- name: Configure LDAP Local SSF
  community.general.ldap_attrs:
    dn: 'cn=config'
    attributes:
      olcLocalSSF: '{{ slapd_ldap_local_ssf }}'
    state: 'exact'

- name: Configure LDAP connection security
  community.general.ldap_attrs:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    attributes:
      olcSecurity: '{{ slapd_ldap_security }}'
    state: 'exact'
  notify: ['Restart slapd']

- name: Configure LDAP indices
  community.general.ldap_attrs:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    attributes:
      olcDbIndex: '{{ slapd_ldap_index }}'
    state: 'exact'

- name: Configure LDAP Access Control List
  community.general.ldap_attrs:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    attributes:
      olcAccess: '{{ lookup("template", "lookup/slapd_ldap_access_control_list.j2") | from_yaml }}'
    state: 'exact'

- name: Configure LDAP limits
  community.general.ldap_attrs:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    attributes:
      olcLimits: '{{ lookup("template", "lookup/slapd_ldap_limits.j2") | from_yaml }}'
    state: 'exact'

- name: Configure LDAP read only flag
  community.general.ldap_attrs:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    attributes:
      olcReadOnly: "{{ 'TRUE' if slapd_read_only else 'FALSE' }}"
    state: 'exact'
