---

- name: Configure domain for OpenLDAP in debconf
  ansible.builtin.debconf:
    name: 'slapd'
    question: '{{ item }}'
    vtype: 'string'
    value: '{{ slapd_domain }}'
  with_items: ['slapd/domain', 'shared/organization']

- name: Configure database backend for OpenLDAP in debconf
  ansible.builtin.debconf:
    name: 'slapd'
    question: 'slapd/backend'
    vtype: 'string'
    value: '{{ slapd_backend | upper }}'

- name: Install OpenLDAP packages
  ansible.builtin.apt:
    name:
      - 'slapd'
      - 'ldap-utils'
      - 'python3-ldap'
    state: 'present'
    install_recommends: false

- name: Install helper scripts
  ansible.builtin.copy:
    src: 'usr/local/sbin/'
    dest: '/usr/local/sbin/'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Copy custom LDAP schema files
  ansible.builtin.copy:
    src: 'usr/local/etc/ldap/schema/'
    dest: '/usr/local/etc/ldap/schema/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Load custom LDAP schema files
  ansible.builtin.command: load-ldap-schema {{ item }}
  with_items: '{{ slapd_ldap_schema }}'
  register: slapd_register_load_schema
  when: slapd_ldap_schema is defined and slapd_ldap_schema
  changed_when: slapd_register_load_schema.stdout != ""

- name: Set up admin password
  ansible.builtin.import_tasks: password_config_admin.yml

- name: Set LDAP configuration
  ansible.builtin.import_tasks: ldap_configuration.yml
  tags: slapd-config

- name: Set up BaseDN admin password
  ansible.builtin.import_tasks: password_basedn_admin.yml
- name: Set up TLS
  ansible.builtin.import_tasks: tls.yml
- name: Set up anonymous bind
  ansible.builtin.import_tasks: anonymous_bind.yml

- name: Set slapd log level
  community.general.ldap_attrs:
    dn: 'cn=config'
    attributes:
      olcLogLevel: '{{ slapd_log_level }}'
    state: 'exact'


- name: Set up replication
  ansible.builtin.import_tasks: replication.yml
- name: Set up password policy
  ansible.builtin.import_tasks: ppolicy.yml
- name: Set up LDAP memberof groups
  ansible.builtin.import_tasks: memberof.yml

- name: Configure enabled services
  ansible.builtin.lineinfile:
    dest: '/etc/default/slapd'
    regexp: '^SLAPD_SERVICES='
    line: 'SLAPD_SERVICES="{{ slapd_default_services | join(" ") }}"'
    state: 'present'
  notify: ['Restart slapd']

- name: Set up ldapscripts
  ansible.builtin.include_tasks: ldapscripts.yml
  when: slapd_ldapscripts | bool

- name: Create snapshot task in cron
  ansible.builtin.cron:
    name: 'Create snapshots of OpenLDAP database'
    special_time: '{{ slapd_snapshot_period }}'
    cron_file: 'ansible_slapd-snapshot'
    user: 'root'
    state: 'present'
    job: '/usr/local/sbin/slapd-snapshot {{ slapd_snapshot_period }} 30'
  when: slapd_snapshot | bool
