---

- name: Generate config administrator password hash
  command: slappasswd -s {{ slapd_config_admin_password }}
  register: slapd_register_config_admin_hash
  changed_when: False
  no_log: True

- name: Set config administrator password
  ldap_attr:
    dn: 'olcDatabase={0}config,cn=config'
    name: '{{ item.key }}'
    values: '{{ item.value }}'
    state: 'exact'
  with_dict:
    olcRootDN: 'cn=admin,cn=config'
    olcRootPW: '{{ slapd_register_config_admin_hash.stdout }}'
  no_log: True
