---

- name: Generate BaseDN administrator password hash
  command: "python3 -c 'import crypt; print(\"{CRYPT}\" + crypt.crypt(\"{{ slapd_basedn_admin_password }}\", crypt.mksalt(crypt.METHOD_SHA512)))'"
  register: slapd_register_basedn_admin_hash
  changed_when: False
  check_mode: no
  no_log: True

# TODO: Skip if the password is already valid
- name: Set BaseDN administrator password
  ldap_attrs:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    attributes:
      olcRootDN: '{{ slapd_basedn_admin }}'
      olcRootPW: '{{ slapd_register_basedn_admin_hash.stdout }}'
    state: 'exact'
  no_log: True

- name: Set BaseDN administrator password
  ldap_attrs:
    dn: '{{ slapd_basedn_admin }}'
    attributes:
      userPassword: '{{ slapd_register_basedn_admin_hash.stdout }}'
    state: 'exact'
  when: not slapd_read_only
  no_log: True
