---

- name: Generate BaseDN administrator password hash
  command: "python3 -c 'import crypt; print(\"{CRYPT}\" + crypt.crypt(\"{{ slapd_basedn_admin_password }}\", crypt.mksalt(crypt.METHOD_SHA512)))'"
  register: slapd_register_basedn_admin_hash
  changed_when: False
  no_log: True

- name: Set BaseDN administrator
  ldap_attr:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    name: '{{ item.key }}'
    values: '{{ item.value }}'
    state: 'exact'
  with_dict:
    olcRootDN: '{{ slapd_basedn_admin }}'
    olcRootPW: '{{ slapd_register_basedn_admin_hash.stdout }}'
  no_log: True

- name: Set BaseDN administrator
  ldap_attr:
    dn: '{{ slapd_basedn_admin }}'
    name: 'userPassword'
    values: '{{ slapd_register_basedn_admin_hash.stdout }}'
    state: 'exact'
  no_log: True
