---

- name: Generate config administrator password hash
  command: "python3 -c 'import crypt; print(\"{CRYPT}\" + crypt.crypt(\"{{ slapd_config_admin_password }}\", crypt.mksalt(crypt.METHOD_SHA512)))'"
  register: slapd_register_config_admin_hash
  changed_when: False
  check_mode: no
  no_log: True

# TODO: Skip if the password is already valid
- name: Set config administrator password
  community.general.ldap_attrs:
    dn: 'olcDatabase={0}config,cn=config'
    attributes:
      olcRootDN: 'cn=admin,cn=config'
      olcRootPW: '{{ slapd_register_config_admin_hash.stdout }}'
    state: 'exact'
  no_log: True
